"""empty message

Revision ID: 4b0d4058a89c
Revises: 2e1228768e0a
Create Date: 2021-03-29 11:32:52.459298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0d4058a89c'
down_revision = '2e1228768e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('musical', 'theater_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('musical', 'theater_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
